routes/web.php
<?php

use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\VttController;
use App\Http\Controllers\testcontroller;
use App\Http\Controllers\UserController;
use Spatie\Permission\Models\Permission;
use App\Http\Controllers\GarageController;
use App\Http\Controllers\MissionController;
use App\Http\Controllers\VehiculeController;
use App\Http\Controllers\VignetteController;
use App\Http\Controllers\CarburantController;
use App\Http\Controllers\ChaufeureController;
use App\Http\Controllers\EntretienController;
use App\Http\Controllers\AssauranceController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ReparationController;
use App\Http\Controllers\CarnetCarburantController;
use App\Http\Controllers\VisiteTechniqueController;
use App\Http\Controllers\Entreprise_assaurance_Controller;

//
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


  
// Route::group(['middleware' => ['auth']], function() {
//     Route::resource('roles', RoleController::class);
//     Route::resource('users', UserController::class);
//     Route::resource('products', ProductController::class);
// });





Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('0');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


// ---------------------------Admins----------------------

Route::group(['middleware' => ['role:Super Admin|Admin']], function () {

    Route::get('permission/{role}/{permission}/', [PermissionController::class, 'togglePrmission'])->name('toogle');
    Route::resource('Users', UserController::class)->except(['show'])->middleware('auth');
    Route::get('add_users', [UserController::class, 'create'])->name('add_users');
    Route::post('store_users', [UserController::class, 'store'])->name('store_users');

    Route::PUT('update_user/{id}', [UserController::class, 'update'])->name('update_user');

    Route::get('permission', [PermissionController::class, 'index'])->name('permission');
    // Route::get('tst', [testcontroller::class, 'index'])->name('tst');

});

// ---------------------------Vehicules----------------------

Route::resource('vehicules', VehiculeController::class)->except(['show'])->middleware('auth');
Route::get('vehicules/archive', [VehiculeController::class, 'archive'])->middleware('auth')->name('archiveVehicule');
Route::patch('vehicules/{id}/restore', [VehiculeController::class, 'restore'])->middleware('auth')->name('restoreVehicule');
Route::delete('vehicules/{id}/forcedelete', [VehiculeController::class, 'forcedelete'])->middleware('auth')->name('forcedelete');

// ---------------------------Chaufeures---------------------------------------------------------------

Route::resource('chaufeures', ChaufeureController::class)->except(['show'])->middleware('auth');
Route::get('chaufeures/archive', [ChaufeureController::class, 'archive'])->middleware('auth')->name('archiveChaufeure');
Route::patch('chaufeures/{id}/restore', [ChaufeureController::class, 'restore'])->middleware('auth')->name('restoreChaufeure');

// ----------------------------Carnet Carburant--------------------------------------------------------
Route::resource('CarnetCarburant', CarnetCarburantController::class)->except(['show','edit','destroy','update'])->middleware('auth');

Route::get('CarnetCarburant/archive', [CarnetCarburantController::class, 'archive'])->middleware('auth')->name('archivecarnet');

// ----------------------------Mission-----------------------------------------------------------------
Route::resource('mission', MissionController::class)->except(['show'])->middleware('auth');

// ----------------------------Garages-----------------------------------------------------------------
Route::resource('Garages', GarageController::class)->except(['show'])->middleware('auth');

// ----------------------------Reparation--------------------------------------------------------------
Route::resource('Reparation', ReparationController::class)->except(['show'])->middleware('auth');

// ----------------------------Assaurance--------------------------------------------------------------
Route::resource('Assaurance', AssauranceController::class)->except(['show'])->middleware('auth');

// ----------------------------Entreprise Assaurance---------------------------------------------------
Route::resource('Entreprise_assaurance', Entreprise_assaurance_Controller::class)->except(['show'])->middleware('auth');

// ----------------------------Vignette----------------------------------------------------------------
Route::resource('Vignette', VignetteController::class)->except(['show'])->middleware('auth');

// ----------------------------Carburant---------------------------------------------------------------
Route::resource('Carburant', CarburantController::class)->except(['show'])->middleware('auth');

// ----------------------------Visite Technique--------------------------------------------------------
Route::resource('VisiteTechnique', VisiteTechniqueController::class)->except(['show'])->middleware('auth');

// ----------------------------Visite Technique--------------------------------------------------------
Route::resource('VTT', VttController::class)->except(['show'])->middleware('auth');

// ----------------------------Entretien---------------------------------------------------------------
Route::resource('Entretien', EntretienController::class)->except(['show'])->middleware('auth');
// ->only('index','store','create','destroy');

// ----------------------------export---------------------------------------------------------------
Route::get('/Vehicules_to_excel', [App\Http\Controllers\VehiculeController::class, 'exportexcel'])->middleware('auth');
// Route::get('/Vehicules_to_csv', [App\Http\Controllers\VehiculeController::class, 'exportCSV'])->middleware('auth');

// ----------------------------Auth---------------------------------------------------------------

Auth::routes(['register' => false]);


// Route::get('/login', [LoginController::class, 'authenticated'])->name('login');

resources/views/carburant-view/create.blade.php
@extends('layouts.app')

@section('title')
Ajouter Carburant 
@endsection

@section('content') 

<center>
    <h1 class="mt-4"><span class="text-uppercase">AJOUTER CARBURANT</span></h1>
</center>
<div class="container">
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active"><a href="/Carburant">Carburants &nbsp;</a><a href="/Carburant/create">/ Ajouter</a>
        </li>
    </ol>
</div>

<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">
                <h3>Ajouter Nouveau Carburant</h3>
            </div>
            <div class="card-body">

                      <form id="add-form" method="post" action="{{ route('Carburant.store') }}" role="form">
                        @csrf
                        <div class="messages"></div>
                        <div class="controls">

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="vehicule_id">Vehicule :<span style="color: red"> *</span></label>
                                        <select id="vehicule_id" name="vehicule_id" class="form-control @if($errors->get('vehicule_id')) border border-danger @endif" required="required">
                                            <option value="" selected disabled>selectionner une vehicule</option>
                                            @foreach ($liste_vehicule as $vehicule)
                                                @if (old('vehicule_id') == $vehicule->id)
                                                    <option value="{{ $vehicule->id }}" selected>{{ $vehicule->type}} : {{ $vehicule->marque}} {{ $vehicule->immatriculation }}</option>
                                                @else
                                                    <option value="{{ $vehicule->id }}">{{ $vehicule->type}} : {{ $vehicule->marque}} {{ $vehicule->immatriculation }}</option>
                                                @endif
                                            @endforeach
                                        </select>
                                        <span style="color: red">@error('vehicule_id'){{$message}}@enderror</span>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="chauffeure_id">Chauffeure :<span style="color: red"> *</span></label>
                                        <select id="chauffeure_id" name="chauffeure_id" class="form-control @if($errors->get('chauffeure_id')) border border-danger @endif" required="required" >
                                            
                                            <option value="" selected disabled>selectionner un chauffeure</option>
                                            @foreach ($liste_chauffeure as $chauffeure)
                                                @if (old('chauffeure_id') == $chauffeure->id)
                                                    <option value="{{ $chauffeure->id }}" selected>{{ $chauffeure->nom }} {{ $chauffeure->prenom }}</option>
                                                @else
                                                    <option value="{{ $chauffeure->id }}">{{ $chauffeure->nom }} {{ $chauffeure->prenom }}</option>
                                                @endif
                                            @endforeach
                                        </select>
                                        <span style="color: red">@error('chauffeure_id'){{$message}}@enderror</span>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="date">Date :<span style="color: red"> *</span></label>
                                        <input id="date" type="date" value="{{ old('date') }}" name="date" class="form-control @if($errors->get('date')) border border-danger @endif" required="required" >
                                        <span style="color: red">@error('date'){{$message}}@enderror</span>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                  <div class="form-group">
                                      <label for="Vignette">Vignette</label>
                                      <input id="Vignette" type="TEXT" value="{{ old('Vignette') }}" name="Vignette" class="form-control @if($errors->get('Vignette')) border border-danger @endif" placeholder="Vignette">
                                      <span style="color: red">@error('Vignette'){{$message}}@enderror</span>
                                  </div>
                              </div>
                            </div>
                            
                            <div class="row">
                              <div class="col-md-6">
                                <div class="form-group">
                                    <label for="montant">Montant</label>
                                    <div class="input-group mb-3">
                                        <input id="montant" type="Number" value="{{ old('montant') }}" name="montant" class="form-control @if($errors->get('montant')) border border-danger @endif" placeholder="montant ">
                                        <div class="input-group-append">
                                          <span class="input-group-text">DH</span>
                                        </div>
                                      </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <span style="color: red">@error('montant'){{$message}}@enderror</span>
                            </div>

                          </div>
                          
                          <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="form_message">Observation</label>
                                        <textarea id="Observation" name="Observation" class="form-control @if($errors->get('Observation')) border border-danger @endif" placeholder="Observation" rows="4" >{{ old('Observation') }}</textarea>
                                        <span style="color: red">@error('Observation'){{$message}}@enderror</span>
                                    </div>
                                </div>
                            </div>


                            <div class="row">                             
                                <div class="col-md-12">
                                    <input type="submit" class="btn btn-primary btn-send" value="Ajouter">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <p class="text-muted">
                                        <strong><span style="color: red">* est obligatoire.</span></strong>
                                </div>
                            </div>
                        </div>
    
                    </form>
            </div>
        </div>
      </div>
</div>
@endsection

resources/views/carburant-view/edit.blade.php
@extends('layouts.app')

@section('title')
    Edit Carburant
@endsection

@section('content')

<center> <h1 class="mt-4"><span class="text-uppercase"> MODIFIER Carburant</span></h1> </center>

<div class="container">
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active"><a href="/Carburant">Carburants &nbsp;</a><a href="{{ route('Carburant.edit', $Carburant->id), '/edit' }}">/ Modifier</a>
        </li>
    </ol>
</div>

<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">
                <h3>Modifier Carburant : Referance {{ $Carburant->id }}</h3>
            </div>
            <div class="card-body">
                <form id="add-form" method="POST" action="{{ route('Carburant.update', $Carburant->id) }}" role="form">
                    @csrf
                    @method('PUT')
                    <div class="messages"></div>
                        <div class="controls">

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="vehicule_id">Vehicule :<span style="color: red"> *</span></label>
                                        <select id="vehicule_id" disabled name="vehicule_id" class="form-control">
                                            <option selected>{{ $MyVehicule->marque }} {{ $MyVehicule->immatriculation }}</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="chauffeure_id">Chauffeure :<span style="color: red"> *</span></label>
                                        <select id="chauffeure_id" disabled class="form-control">
                                            <option selected>{{ $MyChauffeure->nom }} {{ $MyChauffeure->prenom }}</option>
                                        </select>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="date">Date :<span style="color: red"> *</span></label>
                                        <input id="date" type="date" name="date" value="{{ $Carburant->date }}" class="form-control @if ($errors->get('date')) border border-danger @endif" required="required" >
                                        <span style="color: red">@error('date'){{ $message }}@enderror</span>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="Vignette">Vignette</label>
                                        <input id="Vignette" type="TEXT" name="Vignette" value="{{ $Carburant->Vignette }}" class="form-control @if ($errors->get('Vignette')) border border-danger @endif" placeholder="Vignette">
                                        <span style="color: red">@error('Vignette'){{ $message }}@enderror</span>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="montant">Montant</label>
                                        <div class="input-group mb-3">
                                            <input id="montant" type="Number" name="montant" value="{{ $Carburant->montant }}" class="form-control @if ($errors->get('montant')) border border-danger @endif" placeholder="montant ">
                                            <div class="input-group-append">
                                                <span class="input-group-text">DH</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <span style="color: red">@error('montant'){{ $message }}@enderror</span>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="form_message">Observation</label>
                                        <textarea id="Observation" name="Observation" class="form-control @if ($errors->get('Observation')) border border-danger @endif" placeholder="Observation" rows="4" >{{ $Carburant->Observation }}</textarea>
                                        <span style="color: red">@error('Observation'){{ $message }}@enderror</span>
                                    </div>
                                </div>
                            </div>

                           <div class="row">
                                <div class="col-md-12">
                                    <input type="submit" class="btn btn-primary btn-send" value="Modifier">
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <p class="text-muted">
                                    <strong><span style="color: red">* est obligatoire.</span></strong>
                                </div>
                            </div>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/carburant-view/index.blade.php
@extends('layouts.app')

@section('title')
    index Carburant
@endsection

@section('content')

    <center>
        <h1 class="mt-4"><span class="text-uppercase">LISTE DES CARBURANTS</span></h1>
    </center>
    <div class="container">
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active"><a href="/Carburant">Carburants</a> </li>
        </ol>
    </div>

@can('create carburant')
    <center>
        <a class="btn btn-primary" style="font-size: 20px" href="{{ route('Carburant.create') }} "> <i class="fas fa-plus-square"></i><span> Ajouter une Carburant</a>
    </center>
@endcan
<BR>

    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover" id="dataTable" width="100%" cellspacing="0">
                        <thead class="text-primary">
                            <tr>
                                <td style="border:none;white-space: nowrap"><span class="text-uppercase">#</span></td>
                                <td style="border:none;white-space: nowrap"><span class="text-uppercase">Vehicule</span></td>
                                <td style="border:none;white-space: nowrap"><span class="text-uppercase">Chauffeure</span></td>
                                <td style="border:none;white-space: nowrap"><span class="text-uppercase">Date</span></td>
                                <td style="border:none;white-space: nowrap"><span class="text-uppercase">Vignette</span></td>
                                <td style="border:none;white-space: nowrap"><span class="text-uppercase">Montant</span></td>
                                <td style="border:none;white-space: nowrap"><span class="text-uppercase">Observation</span></td>
                                 @can('edit carburant')
                                    <td style="border:none;white-space: nowrap"><span class="text-uppercase">Action</span></th>
                                @endcan 
                            </tr>
                        </thead>
                        <tbody id="myTable">
                            @forelse($Carburants as $Carburant)
                                <tr>
                                    <td>
                                        <a>{{ $Carburant->id }}</a>
                                    </td>
                                    <td>
                                        @if ($Carburant->vehicule_id == null)
                                            <span style="color: red">---</span>
                                        @else
                                            @foreach ($liste_vehicule as $vehicule)
                                                @if ($Carburant->vehicule_id == $vehicule->id)

                                                    @if ($vehicule->type == 'Voiture')
                                                        <i class="fas fa-car"></i>
                                                    @else
                                                        @if ($vehicule->type == 'Moto' || $vehicule->type == 'Velo')
                                                            <i class="fas fa-bicycle"></i>
                                                        @else
                                                            @if ($vehicule->type == 'Bus' || $vehicule->type == 'MiniBus')
                                                                <i class="fas fa-bus-alt"></i>
                                                            @endif
                                                        @endif
                                                    @endif

                                                    {{ $vehicule->type }} : {{ $vehicule->marque }}
                                                    {{ $vehicule->immatriculation }}
                                                @endif
                                            @endforeach
                                        @endif
                                    </td>
                                    <td  style="white-space: nowrap">
                                        @if ($Carburant->chauffeure_id == null)
                                            <span style="color: red">---</span>
                                        @else
                                            @foreach ($liste_chauffeure as $chauffeure)
                                                @if ($Carburant->chauffeure_id == $chauffeure->id)
                                                    {{ $chauffeure->prenom }} {{ $chauffeure->nom }}
                                                @endif
                                            @endforeach
                                        @endif
                                    </td>
                                    <td  style="white-space: nowrap">
                                        @if ($Carburant->date == null)
                                            <span style="color: red">---</span>
                                        @else
                                            {{ $Carburant->date }}
                                        @endif
                                    </td>
                                    <td>
                                        @if ($Carburant->Vignette == null)
                                            <span style="color: red">---</span>
                                        @else
                                            {{ $Carburant->Vignette }}
                                        @endif
                                    </td>
                                    <td>
                                        @if ($Carburant->montant == null)
                                            <span style="color: red">---</span>
                                        @else
                                            {{ $Carburant->montant }} DH
                                        @endif
                                    </td>
                                    <td>
                                        @if ($Carburant->Observation == null)
                                            <span style="color: red">---</span>
                                        @else
                                            {{ $Carburant->Observation }}
                                        @endif
                                    </td>
                                    @can('edit carburant')

                                    <td>
                                        <center>
                                            <a href="{{ route('Carburant.edit', $Carburant->id), '/edit' }}"
                                                class="Edit" title="Modifier" data-toggle="tooltip"><i
                                                    class="fas fa-edit fa-lg"></i></i></a>
                                            {{-- <a href="#" class="delete" title="Supprimer" data-toggle="modal"
                                                data-target="#exampleModal-{{ $Carburant->id }}"
                                                data-whatever="{{ $Carburant->id }}"><i
                                                    class="fas fa-trash-alt fa-lg"></i></a> --}}
                                                    
                                            {{-- Model --}}
                                            {{-- <div class="modal fade" id="exampleModal-{{ $Carburant->id }}" tabindex="-1"
                                                role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                                <form method="POST"
                                                    action="{{ route('Carburant.destroy', $Carburant->id) }}"
                                                    role="form">
                                                    @csrf
                                                    @method('DELETE')
                                                    <div class="modal-dialog" role="document">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <h5 class="modal-title" id="exampleModalLabel">confirmation
                                                                </h5>
                                                                <input type="hidden" name="dele"
                                                                    value="{{ $Carburant->id }}">
                                                                <button type="button" class="close" data-dismiss="modal"
                                                                    aria-label="Close">
                                                                    <span aria-hidden="true">&times;</span>
                                                                </button>
                                                            </div>
                                                            <div class="modal-body">
                                                                <h3> voulez vous supprimer la Carburant Referance :
                                                                    {{ $Carburant->id }}</h3>
                                                            </div>
                                                            <div class="modal-footer">
                                                                <button type="button" class="btn btn-secondary"
                                                                    data-dismiss="modal">Close</button>
                                                                <input type="submit" class="btn btn-danger btn-send"
                                                                    value="Supprimer">
                                                            </div>
                                                        </div>
                                                    </div>
                                                </form>
                                            </div> --}}
                                        </center>
                                    </td>
                                  @endcan 

                                </tr>
                            @empty
                                <tr>
                                    <td colspan="8">
                                        <div class="card-header"><strong style="color: red">
                                                <center>Aucune Carburant</center>
                                            </strong> </div>
                                    </td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


@endsection