routes/web.php
<?php

use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\VttController;
use App\Http\Controllers\testcontroller;
use App\Http\Controllers\UserController;
use Spatie\Permission\Models\Permission;
use App\Http\Controllers\GarageController;
use App\Http\Controllers\MissionController;
use App\Http\Controllers\VehiculeController;
use App\Http\Controllers\VignetteController;
use App\Http\Controllers\CarburantController;
use App\Http\Controllers\ChaufeureController;
use App\Http\Controllers\EntretienController;
use App\Http\Controllers\AssauranceController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ReparationController;
use App\Http\Controllers\CarnetCarburantController;
use App\Http\Controllers\VisiteTechniqueController;
use App\Http\Controllers\Entreprise_assaurance_Controller;

//
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


  
// Route::group(['middleware' => ['auth']], function() {
//     Route::resource('roles', RoleController::class);
//     Route::resource('users', UserController::class);
//     Route::resource('products', ProductController::class);
// });





Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('0');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


// ---------------------------Admins----------------------

Route::group(['middleware' => ['role:Super Admin|Admin']], function () {

    Route::get('permission/{role}/{permission}/', [PermissionController::class, 'togglePrmission'])->name('toogle');
    Route::resource('Users', UserController::class)->except(['show'])->middleware('auth');
    Route::get('add_users', [UserController::class, 'create'])->name('add_users');
    Route::post('store_users', [UserController::class, 'store'])->name('store_users');

    Route::PUT('update_user/{id}', [UserController::class, 'update'])->name('update_user');

    Route::get('permission', [PermissionController::class, 'index'])->name('permission');
    // Route::get('tst', [testcontroller::class, 'index'])->name('tst');

});

// ---------------------------Vehicules----------------------

Route::resource('vehicules', VehiculeController::class)->except(['show'])->middleware('auth');
Route::get('vehicules/archive', [VehiculeController::class, 'archive'])->middleware('auth')->name('archiveVehicule');
Route::patch('vehicules/{id}/restore', [VehiculeController::class, 'restore'])->middleware('auth')->name('restoreVehicule');
Route::delete('vehicules/{id}/forcedelete', [VehiculeController::class, 'forcedelete'])->middleware('auth')->name('forcedelete');

// ---------------------------Chaufeures---------------------------------------------------------------

Route::resource('chaufeures', ChaufeureController::class)->except(['show'])->middleware('auth');
Route::get('chaufeures/archive', [ChaufeureController::class, 'archive'])->middleware('auth')->name('archiveChaufeure');
Route::patch('chaufeures/{id}/restore', [ChaufeureController::class, 'restore'])->middleware('auth')->name('restoreChaufeure');

// ----------------------------Carnet Carburant--------------------------------------------------------
Route::resource('CarnetCarburant', CarnetCarburantController::class)->except(['show','edit','destroy','update'])->middleware('auth');

Route::get('CarnetCarburant/archive', [CarnetCarburantController::class, 'archive'])->middleware('auth')->name('archivecarnet');

// ----------------------------Mission-----------------------------------------------------------------
Route::resource('mission', MissionController::class)->except(['show'])->middleware('auth');

// ----------------------------Garages-----------------------------------------------------------------
Route::resource('Garages', GarageController::class)->except(['show'])->middleware('auth');

// ----------------------------Reparation--------------------------------------------------------------
Route::resource('Reparation', ReparationController::class)->except(['show'])->middleware('auth');

// ----------------------------Assaurance--------------------------------------------------------------
Route::resource('Assaurance', AssauranceController::class)->except(['show'])->middleware('auth');

// ----------------------------Entreprise Assaurance---------------------------------------------------
Route::resource('Entreprise_assaurance', Entreprise_assaurance_Controller::class)->except(['show'])->middleware('auth');

// ----------------------------Vignette----------------------------------------------------------------
Route::resource('Vignette', VignetteController::class)->except(['show'])->middleware('auth');

// ----------------------------Carburant---------------------------------------------------------------
Route::resource('Carburant', CarburantController::class)->except(['show'])->middleware('auth');

// ----------------------------Visite Technique--------------------------------------------------------
Route::resource('VisiteTechnique', VisiteTechniqueController::class)->except(['show'])->middleware('auth');

// ----------------------------Visite Technique--------------------------------------------------------
Route::resource('VTT', VttController::class)->except(['show'])->middleware('auth');

// ----------------------------Entretien---------------------------------------------------------------
Route::resource('Entretien', EntretienController::class)->except(['show'])->middleware('auth');
// ->only('index','store','create','destroy');

// ----------------------------export---------------------------------------------------------------
Route::get('/Vehicules_to_excel', [App\Http\Controllers\VehiculeController::class, 'exportexcel'])->middleware('auth');
// Route::get('/Vehicules_to_csv', [App\Http\Controllers\VehiculeController::class, 'exportCSV'])->middleware('auth');

// ----------------------------Auth---------------------------------------------------------------

Auth::routes(['register' => false]);


// Route::get('/login', [LoginController::class, 'authenticated'])->name('login');

resources/views/EntreAss-view/create.blade.php
@extends('layouts.app')

@section('title')
Ajouter Entreprise
@endsection

@section('content')
  

<center>
    <h1 class="mt-4"><span class="text-uppercase">AJOUTER Entreprise d'assaurance</span></h1>
</center>
<div class="container">
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active"><a href="{{ route('Entreprise_assaurance.index') }}">Entreprises &nbsp;</a><a href="/Entreprise_assaurance/create">/ Ajouter</a>
        </li>
    </ol>
</div>

<div class="row justify-content-center">
<div class="col-md-8">
<div class="card">
<div class="card-header"><h3>Ajouter une Entreprise d'assaurance</h3></div>
<div class="card-body"> 

<form id="add-form" method="post" action="{{ route('Entreprise_assaurance.store') }}" role="form">
    <div class="messages"></div>
    @csrf
    <div class="controls">

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="NomAssaurance">Nom d'entreprise :<span style="color: red"> *</span></label>
                    <input id="NomAssaurance" value="{{ old('NomAssaurance') }}" type="text" name="NomAssaurance" class="form-control @if($errors->get('NomAssaurance')) border border-danger @endif" placeholder="Nom d'entreprise" required="required" data-error="Nom d'entreprise est obligatoire.">
                    <span style="color: red">@error('NomAssaurance'){{$message}}@enderror</span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="Address">Address :</label>
                    <input id="Address" value="{{ old('Address') }}" type="text" name="Address" class="form-control @if($errors->get('Address')) border border-danger @endif" placeholder="Address">
                    <span style="color: red">@error('Address'){{$message}}@enderror</span>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="Telephone">Telephone :</label>
                    <input id="Telephone" value="{{ old('Telephone') }}" type="text" name="Telephone" class="form-control @if($errors->get('Telephone')) border border-danger @endif" placeholder="Telephone : 0...">
                    <span style="color: red">@error('Telephone'){{$message}}@enderror</span>
                </div>
            </div>
                                
            <div class="col-md-12">
                <input type="submit" class="btn btn-primary btn-send" value="Ajouter">
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <p class="text-muted">
                    <strong><span style="color: red">* est obligatoire.</span></strong>
            </div>
        </div>
        
    </div>
    
</form>


</div>
</div>
</div>
</div>
@endsection

resources/views/EntreAss-view/edit.blade.php
@extends('layouts.app')

@section('title')
Edit l'entreprise
@endsection

@section('content')
  
<center>
    <h1 class="mt-4"><span class="text-uppercase"> MODIFIER entreprise d'Assaurance</span></h1>
</center>
<div class="container">
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active"><a href="/Entreprise_assaurance">Entreprises &nbsp;</a><a
                href="{{ route('Entreprise_assaurance.edit', $EntreAss->id), '/edit' }}">/ Modifier</a>
        </li>
    </ol>
</div>
<div class="row justify-content-center">
<div class="col-md-8">
<div class="card">
<div class="card-header"><h3>Modifier : {{$EntreAss->NomAssaurance}}</h3>  </div>
<div class="card-body"> 

<form id="add-form" method="post" action="{{ route('Entreprise_assaurance.update', $EntreAss->id ) }}" role="form">
    @csrf
    @method('PUT')
    <div class="messages"></div>
        <div class="controls">

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="NomAssaurance">Nom d'entreprise :<span style="color: red"> *</span></label>
                        <input id="NomAssaurance" type="text" value="{{ $EntreAss->NomAssaurance }}" disabled class="form-control" placeholder="NomAssaurance" required="required" data-error="NomAssaurance est obligatoire.">
                        <span style="color: red">@error('NomAssaurance'){{$message}}@enderror</span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="Address">Address :</label>
                    <input id="Address" type="text" value="{{ $EntreAss->Address }}" name="Address" class="form-control @if($errors->get('Address')) border border-danger @endif" placeholder="Address">
                    <span style="color: red">@error('Address'){{$message}}@enderror</span>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="Telephone">Telephone :</label>
                    <input id="Telephone" type="text" value="{{ $EntreAss->Telephone }}" name="Telephone" class="form-control @if($errors->get('Telephone')) border border-danger @endif" placeholder="Telephone">
                    <span style="color: red">@error('Telephone'){{$message}}@enderror</span>
                </div>
            </div>
        </div>
 
        <div class="col-md-12">
            <input type="submit" class="btn btn-primary btn-send" value="Modifier">
        </div>
                            
        <div class="row">
            <div class="col-md-12">
                <p class="text-muted">             
                            <strong><span style="color: red">* est obligatoire.</span></strong>
            </div>
        </div>
    </div>
</form>

</div>
</div>
</div>
</div>
@endsection

resources/views/EntreAss-view/index.blade.php
@extends('layouts.app')

@section('title')
index Entreprise d'assaurance
@endsection
   
@section('content')

<center>
    <h1 class="mt-4"><span class="text-uppercase">LISTE DES Entreprises d'assaurance</span></h1>
</center>
<div class="container">
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active"><a href="/Entreprise_assaurance">Entreprises /</a> </li>
    </ol>
</div>

@can('create entreAss')
<center>
    <a class="btn btn-primary" style="font-size: 20px" href="{{ route('Entreprise_assaurance.create') }} "><i class="fas fa-plus-square" ></i><span> Ajouter nouvelle Entreprise</a>
</center><BR>
@endcan 
<div class="col-md-12">
    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover" id="dataTable" width="100%" cellspacing="0">
                    <thead class="text-primary">

        <tr>
            <td style="border:none;white-space: nowrap" class="text-uppercase">#</td>
            <td style="border:none;white-space: nowrap" class="text-uppercase">Nom d'entreprise</td>
            <td style="border:none;white-space: nowrap" class="text-uppercase">Address</td>
            <td style="border:none;white-space: nowrap" class="text-uppercase">Telephone</td>
            @can('edit entreAss')
                <td style="border:none;white-space: nowrap" class="text-uppercase"><center>Action</center></td>
            @endcan 

        </tr>
    </thead>
    <tbody id="myTable">   
     
        @forelse($EntreAss as $Entre)
    <tr>
        <td>
            {{$Entre->id}}
        </td>
    
        <td>
            @if ($Entre->NomAssaurance == null)
                <span style="color: red">---</span>
            @else
                {{$Entre->NomAssaurance}}
            @endif
        </td>
        <td>
            @if ($Entre->Address == null)
                <span style="color: red">---</span>
            @else
                {{$Entre->Address}}
            @endif
        </td>
        <td>
            @if ($Entre->Telephone == null)
                <span style="color: red">---</span>
            @else
                {{$Entre->Telephone}}
            @endif    
        </td> 
        @can('edit entreAss')
        <td>
            <center>
                <a href="{{ route('Entreprise_assaurance.edit' , $Entre->id ),'/edit' }}" class="Edit" title="Modifier" data-toggle="tooltip"><i class="fas fa-edit fa-lg"></i></i></a>
                {{-- <a href="#" class="delete" title="Supprimer" data-toggle="modal" data-target="#exampleModal-{{ $Entre->id }}" data-whatever="{{ $Entre->id }}" ><i class="fas fa-trash-alt fa-lg"></i></a>       --}}

                    {{-- Model --}}
                {{-- <div class="modal fade" id="exampleModal-{{ $Entre->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <form method="POST" action="{{ route('Entreprise_assaurance.destroy' , $Entre->id ) }}" role="form">
                        @csrf
                        @method('DELETE')
                        <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">confirmation</h5>
                            <input type="hidden" name="dele" value="{{ $Entre->id }}">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            </div>
                            <div class="modal-body">
                                <h3> voulez vous supprimer l'entreprise : {{ $Entre->NomAssaurance }}</h3>
                            </div>
                            <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <input type="submit" class="btn btn-danger btn-send" value="Supprimer">
                            </div>
                        </div>
                        </div>
                    </form>
                </div> --}}
            </center>                            
        </td>
        @endcan 

    </tr> 
    @empty  
    <tr>
        <td colspan="5">
            <div class="card-header"><strong style="color: red"> <center>Aucune Entreprise d'assaurance</center> </strong> </div>
        </td>
    </tr>
    @endforelse 




     

</tbody>
</table>


</div>
</div>        
</div>
@endsection