routes/web.php
<?php

use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\VttController;
use App\Http\Controllers\testcontroller;
use App\Http\Controllers\UserController;
use Spatie\Permission\Models\Permission;
use App\Http\Controllers\GarageController;
use App\Http\Controllers\MissionController;
use App\Http\Controllers\VehiculeController;
use App\Http\Controllers\VignetteController;
use App\Http\Controllers\CarburantController;
use App\Http\Controllers\ChaufeureController;
use App\Http\Controllers\EntretienController;
use App\Http\Controllers\AssauranceController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ReparationController;
use App\Http\Controllers\CarnetCarburantController;
use App\Http\Controllers\VisiteTechniqueController;
use App\Http\Controllers\Entreprise_assaurance_Controller;

//
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


  
// Route::group(['middleware' => ['auth']], function() {
//     Route::resource('roles', RoleController::class);
//     Route::resource('users', UserController::class);
//     Route::resource('products', ProductController::class);
// });





Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('0');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


// ---------------------------Admins----------------------

Route::group(['middleware' => ['role:Super Admin|Admin']], function () {

    Route::get('permission/{role}/{permission}/', [PermissionController::class, 'togglePrmission'])->name('toogle');
    Route::resource('Users', UserController::class)->except(['show'])->middleware('auth');
    Route::get('add_users', [UserController::class, 'create'])->name('add_users');
    Route::post('store_users', [UserController::class, 'store'])->name('store_users');

    Route::PUT('update_user/{id}', [UserController::class, 'update'])->name('update_user');

    Route::get('permission', [PermissionController::class, 'index'])->name('permission');
    // Route::get('tst', [testcontroller::class, 'index'])->name('tst');

});

// ---------------------------Vehicules----------------------

Route::resource('vehicules', VehiculeController::class)->except(['show'])->middleware('auth');
Route::get('vehicules/archive', [VehiculeController::class, 'archive'])->middleware('auth')->name('archiveVehicule');
Route::patch('vehicules/{id}/restore', [VehiculeController::class, 'restore'])->middleware('auth')->name('restoreVehicule');
Route::delete('vehicules/{id}/forcedelete', [VehiculeController::class, 'forcedelete'])->middleware('auth')->name('forcedelete');

// ---------------------------Chaufeures---------------------------------------------------------------

Route::resource('chaufeures', ChaufeureController::class)->except(['show'])->middleware('auth');
Route::get('chaufeures/archive', [ChaufeureController::class, 'archive'])->middleware('auth')->name('archiveChaufeure');
Route::patch('chaufeures/{id}/restore', [ChaufeureController::class, 'restore'])->middleware('auth')->name('restoreChaufeure');

// ----------------------------Carnet Carburant--------------------------------------------------------
Route::resource('CarnetCarburant', CarnetCarburantController::class)->except(['show','edit','destroy','update'])->middleware('auth');

Route::get('CarnetCarburant/archive', [CarnetCarburantController::class, 'archive'])->middleware('auth')->name('archivecarnet');

// ----------------------------Mission-----------------------------------------------------------------
Route::resource('mission', MissionController::class)->except(['show'])->middleware('auth');

// ----------------------------Garages-----------------------------------------------------------------
Route::resource('Garages', GarageController::class)->except(['show'])->middleware('auth');

// ----------------------------Reparation--------------------------------------------------------------
Route::resource('Reparation', ReparationController::class)->except(['show'])->middleware('auth');

// ----------------------------Assaurance--------------------------------------------------------------
Route::resource('Assaurance', AssauranceController::class)->except(['show'])->middleware('auth');

// ----------------------------Entreprise Assaurance---------------------------------------------------
Route::resource('Entreprise_assaurance', Entreprise_assaurance_Controller::class)->except(['show'])->middleware('auth');

// ----------------------------Vignette----------------------------------------------------------------
Route::resource('Vignette', VignetteController::class)->except(['show'])->middleware('auth');

// ----------------------------Carburant---------------------------------------------------------------
Route::resource('Carburant', CarburantController::class)->except(['show'])->middleware('auth');

// ----------------------------Visite Technique--------------------------------------------------------
Route::resource('VisiteTechnique', VisiteTechniqueController::class)->except(['show'])->middleware('auth');

// ----------------------------Visite Technique--------------------------------------------------------
Route::resource('VTT', VttController::class)->except(['show'])->middleware('auth');

// ----------------------------Entretien---------------------------------------------------------------
Route::resource('Entretien', EntretienController::class)->except(['show'])->middleware('auth');
// ->only('index','store','create','destroy');

// ----------------------------export---------------------------------------------------------------
Route::get('/Vehicules_to_excel', [App\Http\Controllers\VehiculeController::class, 'exportexcel'])->middleware('auth');
// Route::get('/Vehicules_to_csv', [App\Http\Controllers\VehiculeController::class, 'exportCSV'])->middleware('auth');

// ----------------------------Auth---------------------------------------------------------------

Auth::routes(['register' => false]);


// Route::get('/login', [LoginController::class, 'authenticated'])->name('login');

resources/views/VTT-view/create.blade.php
@extends('layouts.app')

@section('title')
Ajouter VTT
@endsection
 
@section('content')
  
<center>
    <h1 class="mt-4"><span class="text-uppercase">AJOUTER VTT</span></h1>
</center>
<div class="container">
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active"><a href="{{ route('VTT.index') }}">VTT &nbsp;</a><a href="/VTT/create">/ Ajouter</a>
        </li>
    </ol>
</div>

<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">
                <h3>Ajouter Nouveau VTT</h3>
            </div>
            <div class="card-body">

<form id="add-form" method="post" action="{{ route('VTT.store') }}" role="form">
    <div class="messages"></div>
    @csrf
    <div class="controls">

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="N_Bon">N Bon :<span style="color: red"> *</span></label>
                    <input id="N_Bon" type="text"  value="{{ old('N_Bon') }}" name="N_Bon" class="form-control @if($errors->get('N_Bon')) border border-danger @endif" placeholder="DB N°" required="required" data-error="N_Bon est obligatoire.">
                    <span style="color: red">@error('N_Bon'){{$message}}@enderror</span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="Transporteur">Transporteur :</label>
                    <input id="Transporteur" type="text"  value="{{ old('Transporteur') }}" name="Transporteur" class="form-control @if($errors->get('Transporteur')) border border-danger @endif" placeholder="Transporteur">
                    <span style="color: red">@error('Transporteur'){{$message}}@enderror</span>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="Beneficiare">Bénéficiaire :<span style="color: red"> *</span></label>
                    <input id="Beneficiare" type="text"  value="{{ old('Beneficiare') }}" name="Beneficiare" class="form-control @if($errors->get('Beneficiare')) border border-danger @endif" placeholder="Beneficiare" required="required" data-error="Beneficiare est obligatoire.">
                    <span style="color: red">@error('Beneficiare'){{$message}}@enderror</span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="From">De :</label>
                    <input id="From" type="text"  value="{{ old('From') }}" name="From" class="form-control @if($errors->get('From')) border border-danger @endif" placeholder="De ">
                    <span style="color: red">@error('From'){{$message}}@enderror</span>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="To">A :</label>
                    <input id="To" type="text"  value="{{ old('To') }}" name="To" class="form-control @if($errors->get('To')) border border-danger @endif" placeholder="A">
                    <span style="color: red">@error('To'){{$message}}@enderror</span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="Montant">Montant :<span style="color: red"> *</span></label>
                    <input id="Montant" type="Number"  value="{{ old('Montant') }}" name="Montant" class="form-control @if($errors->get('Montant')) border border-danger @endif" placeholder="Montant" required="required" data-error="Montant est obligatoire.">
                    <span style="color: red">@error('Montant'){{$message}}@enderror</span>
                </div>
            </div>
        </div>
        <div class="row">
        
                                
            <div class="col-md-12">
                <input type="submit" class="btn btn-primary btn-send" value="Ajouter">
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <p class="text-muted">
                    <strong><span style="color: red">* est obligatoire.</span></strong>
            </div>
        </div>
        
    </div>
    
</form>


</div>
</div>
</div>
</div>

@endsection

resources/views/VTT-view/edit.blade.php
@extends('layouts.app')

@section('title')
edit VTT
@endsection
 
@section('content')

<center>
    <h1 class="mt-4"><span class="text-uppercase">MODIFIER VTT</span></h1>
</center>
<div class="container">
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active"><a href="/VTT">VTT &nbsp;</a><a href="{{ route('VTT.edit', $VTT->id), '/edit' }}">/ Modifier</a>
        </li>
    </ol>
</div>


<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">
                <h3>Modifier VTT : {{ $VTT->id}}</h3>
            </div>
            <div class="card-body">


<form id="add-form" method="post" action="{{ route('VTT.update' , ['VTT' => $VTT->id]) }}" role="form">
    <div class="messages"></div>
    @csrf
      @method('PUT')
    <div class="controls">

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="N_Bon">N Bon :<span style="color: red"> *</span></label>
                    <input id="N_Bon" type="text"  value="{{  $VTT->N_Bon  }}" disabled class="form-control @if($errors->get('N_Bon')) border border-danger @endif" placeholder="DB N°" required="required" data-error="N_Bon est obligatoire.">
                    <span style="color: red">@error('N_Bon'){{$message}}@enderror</span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="Transporteur">Transporteur :</label>
                    <input id="Transporteur" type="text"  value="{{  $VTT->Transporteur  }}" name="Transporteur" class="form-control @if($errors->get('Transporteur')) border border-danger @endif" placeholder="Transporteur">
                    <span style="color: red">@error('Transporteur'){{$message}}@enderror</span>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="Beneficiare">Bénéficiaire :<span style="color: red"> *</span></label>
                    <input id="Beneficiare" type="text"  value="{{  $VTT->Beneficiare  }}" name="Beneficiare" class="form-control @if($errors->get('Beneficiare')) border border-danger @endif" placeholder="Beneficiare" required="required" data-error="Beneficiare est obligatoire.">
                    <span style="color: red">@error('Beneficiare'){{$message}}@enderror</span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="From">De :</label>
                    <input id="From" type="text"  value="{{  $VTT->From  }}" name="From" class="form-control @if($errors->get('From')) border border-danger @endif" placeholder="De ">
                    <span style="color: red">@error('From'){{$message}}@enderror</span>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="To">A :</label>
                    <input id="To" type="text"  value="{{  $VTT->To  }}" name="To" class="form-control @if($errors->get('To')) border border-danger @endif" placeholder="A">
                    <span style="color: red">@error('To'){{$message}}@enderror</span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="Montant">Montant :<span style="color: red"> *</span></label>
                    <input id="Montant" type="Number"  value="{{ $VTT->Montant }}" name="Montant" class="form-control @if($errors->get('Montant')) border border-danger @endif" placeholder="Montant" required="required" data-error="Montant est obligatoire.">
                    <span style="color: red">@error('Montant'){{$message}}@enderror</span>
                </div>
            </div>
        </div>
        <div class="row">
        
                                
            <div class="col-md-12">
                <input type="submit" class="btn btn-primary btn-send" value="Modifier">
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <p class="text-muted">
                    <strong><span style="color: red">* est obligatoire.</span></strong>
            </div>
        </div>
        
    </div>
    
</form>


</div>
</div>
</div>
</div>

@endsection

resources/views/VTT-view/index.blade.php
@extends('layouts.app')

@section('title')
    index VTT
@endsection

@section('content')

    <center>
        <h1 class="mt-4"><span class="text-uppercase">Liste des Bons Transport Terrestre</span></h1>
    </center>
    <div class="container">
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active"><a href="/VTT">VTT /</a> </li>
        </ol>
    </div>
@can('create vtt')
    <center>
        <a class="btn btn-primary" style="font-size: 20px" href="{{ route('VTT.create') }} "><i
                class="fas fa-plus-square"></i><span> Ajouter Bon de Transport</a>
    </center>
@endcan 
<BR>
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover" id="dataTable" width="100%" cellspacing="0">
                        <thead class="text-primary">
                            <tr>
                                <td style="border:none;white-space: nowrap" class="text-uppercase">Date</td>
                                <td style="border:none;white-space: nowrap" class="text-uppercase">N Bon</td>
                                <td style="border:none;white-space: nowrap" class="text-uppercase">Bénéficiaire</td>
                                <td style="border:none;white-space: nowrap" class="text-uppercase">De</td>
                                <td style="border:none;white-space: nowrap" class="text-uppercase">A</td>
                                <td style="border:none;white-space: nowrap" class="text-uppercase">Montant</td>
                                <td style="border:none;white-space: nowrap" class="text-uppercase">Transporteur</td>
                                @canany(['edit vtt', 'delete vtt'])
                                    <td style="border:none;white-space: nowrap" class="text-uppercase">Action</td>
                                @endcan
                            </tr>
                        </thead>
                        <tbody id="myTable">

                            @forelse($VTTs as $VTT)
                                <tr>
                                    <td>
                                        @if ($VTT->date == null)
                                            <span style="color: red">---</span>
                                        @else
                                            {{ $VTT->date }}
                                        @endif
                                    </td>
                                    <td>
                                        @if ($VTT->N_Bon == null)
                                            <span style="color: red">---</span>
                                        @else
                                            {{ $VTT->N_Bon }}
                                        @endif
                                    </td>
                                    <td>
                                        @if ($VTT->Beneficiare == null)
                                            <span style="color: red">---</span>
                                        @else
                                            {{ $VTT->Beneficiare }}
                                        @endif
                                    </td>
                                    <td>
                                        @if ($VTT->From == null)
                                            <span style="color: red">---</span>
                                        @else
                                            {{ $VTT->From }}
                                        @endif
                                    </td>
                                    <td>
                                        @if ($VTT->To == null)
                                            <span style="color: red">---</span>
                                        @else
                                            {{ $VTT->To }}
                                        @endif
                                    </td>
                                    <td>
                                        @if ($VTT->Montant == 0)
                                            <span style="color: red">0</span>
                                        @else
                                            {{ $VTT->Montant }}
                                        @endif
                                    </td>
                                    <td>
                                        @if ($VTT->Transporteur == null)
                                            <span style="color: red">---</span>
                                        @else
                                            {{ $VTT->Transporteur }}
                                        @endif
                                    </td>
                                    <td>
                                        <center>
                                            @can('edit vtt')
                                                <a href="{{ route('VTT.edit', $VTT->id), '/edit' }}" class="Edit" title="Modifier" data-toggle="tooltip"><i class="fas fa-edit fa-lg"></i></i></a>
                                            @endcan

                                            @can('delete vtt')
                                            <a href="#" class="delete" title="Supprimer" data-toggle="modal"
                                                data-target="#exampleModal-{{ $VTT->id }}"
                                                data-whatever="{{ $VTT->id }}"><i
                                                    class="fas fa-trash-alt fa-lg"></i></a>

                                            <div class="modal fade" id="exampleModal-{{ $VTT->id }}" tabindex="-1"
                                                role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                                <form method="POST" action="{{ route('VTT.destroy', $VTT->id) }}"
                                                    role="form">
                                                    @csrf
                                                    @method('DELETE')
                                                    <div class="modal-dialog" role="document">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <h5 class="modal-title" id="exampleModalLabel">confirmation
                                                                </h5>
                                                                <input type="hidden" name="dele"
                                                                    value="{{ $VTT->id }}">
                                                                <button type="button" class="close" data-dismiss="modal"
                                                                    aria-label="Close">
                                                                    <span aria-hidden="true">&times;</span>
                                                                </button>
                                                            </div>
                                                            <div class="modal-body">
                                                                <h3> voulez vous supprimer ce Bon</h3>
                                                            </div>
                                                            <div class="modal-footer">
                                                                <button type="button" class="btn btn-secondary"
                                                                    data-dismiss="modal">Close</button>
                                                                <input type="submit" class="btn btn-danger btn-send"
                                                                    value="Supprimer">
                                                            </div>
                                                        </div>
                                                    </div>
                                                </form>
                                            </div>
                                            @endcan

                                        </center>

                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="8">
                                        <div class="card-header"><strong style="color: red">
                                                <center>Aucune Bon de Transport</center>
                                            </strong> </div>
                                    </td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    @endsection