routes/web.php
<?php

use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\VttController;
use App\Http\Controllers\testcontroller;
use App\Http\Controllers\UserController;
use Spatie\Permission\Models\Permission;
use App\Http\Controllers\GarageController;
use App\Http\Controllers\MissionController;
use App\Http\Controllers\VehiculeController;
use App\Http\Controllers\VignetteController;
use App\Http\Controllers\CarburantController;
use App\Http\Controllers\ChaufeureController;
use App\Http\Controllers\EntretienController;
use App\Http\Controllers\AssauranceController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ReparationController;
use App\Http\Controllers\CarnetCarburantController;
use App\Http\Controllers\VisiteTechniqueController;
use App\Http\Controllers\Entreprise_assaurance_Controller;

//
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


  
// Route::group(['middleware' => ['auth']], function() {
//     Route::resource('roles', RoleController::class);
//     Route::resource('users', UserController::class);
//     Route::resource('products', ProductController::class);
// });





Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('0');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


// ---------------------------Admins----------------------

Route::group(['middleware' => ['role:Super Admin|Admin']], function () {

    Route::get('permission/{role}/{permission}/', [PermissionController::class, 'togglePrmission'])->name('toogle');
    Route::resource('Users', UserController::class)->except(['show'])->middleware('auth');
    Route::get('add_users', [UserController::class, 'create'])->name('add_users');
    Route::post('store_users', [UserController::class, 'store'])->name('store_users');

    Route::PUT('update_user/{id}', [UserController::class, 'update'])->name('update_user');

    Route::get('permission', [PermissionController::class, 'index'])->name('permission');
    // Route::get('tst', [testcontroller::class, 'index'])->name('tst');

});

// ---------------------------Vehicules----------------------

Route::resource('vehicules', VehiculeController::class)->except(['show'])->middleware('auth');
Route::get('vehicules/archive', [VehiculeController::class, 'archive'])->middleware('auth')->name('archiveVehicule');
Route::patch('vehicules/{id}/restore', [VehiculeController::class, 'restore'])->middleware('auth')->name('restoreVehicule');
Route::delete('vehicules/{id}/forcedelete', [VehiculeController::class, 'forcedelete'])->middleware('auth')->name('forcedelete');

// ---------------------------Chaufeures---------------------------------------------------------------

Route::resource('chaufeures', ChaufeureController::class)->except(['show'])->middleware('auth');
Route::get('chaufeures/archive', [ChaufeureController::class, 'archive'])->middleware('auth')->name('archiveChaufeure');
Route::patch('chaufeures/{id}/restore', [ChaufeureController::class, 'restore'])->middleware('auth')->name('restoreChaufeure');

// ----------------------------Carnet Carburant--------------------------------------------------------
Route::resource('CarnetCarburant', CarnetCarburantController::class)->except(['show','edit','destroy','update'])->middleware('auth');

Route::get('CarnetCarburant/archive', [CarnetCarburantController::class, 'archive'])->middleware('auth')->name('archivecarnet');

// ----------------------------Mission-----------------------------------------------------------------
Route::resource('mission', MissionController::class)->except(['show'])->middleware('auth');

// ----------------------------Garages-----------------------------------------------------------------
Route::resource('Garages', GarageController::class)->except(['show'])->middleware('auth');

// ----------------------------Reparation--------------------------------------------------------------
Route::resource('Reparation', ReparationController::class)->except(['show'])->middleware('auth');

// ----------------------------Assaurance--------------------------------------------------------------
Route::resource('Assaurance', AssauranceController::class)->except(['show'])->middleware('auth');

// ----------------------------Entreprise Assaurance---------------------------------------------------
Route::resource('Entreprise_assaurance', Entreprise_assaurance_Controller::class)->except(['show'])->middleware('auth');

// ----------------------------Vignette----------------------------------------------------------------
Route::resource('Vignette', VignetteController::class)->except(['show'])->middleware('auth');

// ----------------------------Carburant---------------------------------------------------------------
Route::resource('Carburant', CarburantController::class)->except(['show'])->middleware('auth');

// ----------------------------Visite Technique--------------------------------------------------------
Route::resource('VisiteTechnique', VisiteTechniqueController::class)->except(['show'])->middleware('auth');

// ----------------------------Visite Technique--------------------------------------------------------
Route::resource('VTT', VttController::class)->except(['show'])->middleware('auth');

// ----------------------------Entretien---------------------------------------------------------------
Route::resource('Entretien', EntretienController::class)->except(['show'])->middleware('auth');
// ->only('index','store','create','destroy');

// ----------------------------export---------------------------------------------------------------
Route::get('/Vehicules_to_excel', [App\Http\Controllers\VehiculeController::class, 'exportexcel'])->middleware('auth');
// Route::get('/Vehicules_to_csv', [App\Http\Controllers\VehiculeController::class, 'exportCSV'])->middleware('auth');

// ----------------------------Auth---------------------------------------------------------------

Auth::routes(['register' => false]);


// Route::get('/login', [LoginController::class, 'authenticated'])->name('login');

resources/views/Entretien-view/create.blade.php
@extends('layouts.app')

@section('title')
Ajouter Entretien  
@endsection

@section('content')
  
<center>
    <h1 class="mt-4"><span class="text-uppercase">AJOUTER Entretien</span></h1>
</center>
<div class="container">
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active"><a href="{{ route('Entretien.index') }}">Entretiens &nbsp;</a><a href="/Entretien/create">/ Ajouter</a>
        </li>
    </ol>
</div>

<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">
                <h3>Ajouter Nouveau Entretien</h3>
            </div>
            <div class="card-body">

                      <form id="add-form" method="post" action="{{ route('Entretien.store') }}" role="form">
                        @csrf
                        <div class="messages"></div>
                        <div class="controls">

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="vehicule_id">Vehicule :<span style="color: red"> *</span></label>
                                        <select id="vehicule_id" name="vehicule_id" class="form-control @if($errors->get('vehicule_id')) border border-danger @endif" required="required">
                                            <option value="" selected disabled>selectionner une vehicule</option>
                                            @foreach ($liste_vehicule as $vehicule)
                                                @if (old('vehicule_id') == $vehicule->id)
                                                    <option value="{{ $vehicule->id }}" selected>{{ $vehicule->type}} : {{ $vehicule->marque}} {{ $vehicule->immatriculation }}</option>
                                                @else
                                                    <option value="{{ $vehicule->id }}">{{ $vehicule->type}} : {{ $vehicule->marque}} {{ $vehicule->immatriculation }}</option>
                                                @endif
                                            @endforeach
                                        </select>
                                        <span style="color: red">@error('vehicule_id'){{$message}}@enderror</span>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="chauffeure_id">Chauffeure :<span style="color: red"> *</span></label>
                                        <select id="chauffeure_id" name="chauffeure_id" class="form-control @if($errors->get('chauffeure_id')) border border-danger @endif" required="required" >
                                            <option value="" selected disabled>selectionner un chauffeure</option>
                                            @foreach ($liste_chauffeure as $chauffeure)
                                                @if (old('chauffeure_id') == $chauffeure->id)
                                                    <option value="{{ $chauffeure->id }}" selected>{{ $chauffeure->nom }} {{ $chauffeure->prenom }}</option>                                                    
                                                @else
                                                    <option value="{{ $chauffeure->id }}">{{ $chauffeure->nom }} {{ $chauffeure->prenom }}</option>                                    
                                                @endif
                                            @endforeach
                                        </select>
                                        <span style="color: red">@error('chauffeure_id'){{$message}}@enderror</span>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="date">Date  :<span style="color: red"> *</span></label>
                                        <input id="date" type="date" value="{{ old('date') }}" name="date" class="form-control @if($errors->get('date')) border border-danger @endif" required="required" >
                                        <span style="color: red">@error('date'){{$message}}@enderror</span>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="montant_Carburant">Montant Carburant</label>
                                        <div class="input-group mb-3">
                                            <input id="montant_Carburant" value="{{ old('montant_Carburant') }}" type="number" name="montant_Carburant" class="form-control @if($errors->get('montant_Carburant')) border border-danger @endif" placeholder="montant carburant ">
                                            <div class="input-group-append">
                                              <span class="input-group-text">DH</span>
                                            </div>
                                            <span style="color: red">@error('montant_Carburant'){{$message}}@enderror</span>
                                          </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="row">
                                <div class="col-md-6">
                                  <div class="form-group">
                                      <label for="object">Object</label>
                                      <div class="input-group mb-3">
                                          <input id="object" value="{{ old('object') }}" type="text" name="object" class="form-control @if($errors->get('object')) border border-danger @endif" placeholder="object ">
                                        </div>
                                        <span style="color: red">@error('object'){{$message}}@enderror</span>
                                  </div>
                              </div>
  
                              <div class="col-md-6">
                                  <div class="form-group">
                                      <label for="Garage_id">Garage :<span style="color: red"> *</span></label>
                                      <select id="Garage_id" name="Garage_id" class="form-control @if($errors->get('Garage_id')) border border-danger @endif" required="required" >
                                          
                                          <option value="" selected disabled>selectionner un garage</option>
                                          @foreach ($liste_garage as $garage)
                                            @if ( old('Garage_id') == $garage->id)
                                              <option value="{{ $garage->id }}" selected>{{ $garage->NomGarage }}</option>                                                
                                            @else
                                              <option value="{{ $garage->id }}">{{ $garage->NomGarage }}</option>                                                
                                            @endif
                                          @endforeach
                                      </select>
                                      <span style="color: red">@error('Garage_id'){{$message}}@enderror</span>
                                  </div>
                              </div>
  
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="kelometrage">Kelometrage</label>
                                        <div class="input-group mb-3">
                                            <input id="kelometrage" value="{{ old('kelometrage') }}" type="NUMBER" name="kelometrage" class="form-control @if($errors->get('kelometrage')) border border-danger @endif" placeholder="kelometrage">
                                            <div class="input-group-append">
                                                <span class="input-group-text">kilomètre</span>
                                              </div>
                                              <span style="color: red">@error('kelometrage'){{$message}}@enderror</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="N_Souche">N Souche</label>
                                        <div class="input-group mb-3">
                                            <input id="N_Souche" value="{{ old('N_Souche') }}" type="text" name="N_Souche" class="form-control @if($errors->get('N_Souche')) border border-danger @endif" placeholder="Numero de Souche">
                                          </div>
                                          <span style="color: red">@error('N_Souche'){{$message}}@enderror</span>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="observation">Observation</label>
                                        <textarea id="observation" name="observation" class="form-control @if($errors->get('observation')) border border-danger @endif" placeholder="observation" rows="4" >{{ old('observation') }}</textarea>
                                        <span style="color: red">@error('observation'){{$message}}@enderror</span>
                                    </div>
                                </div>
                            </div>
  


                            </div>
                          
                            <div class="row">                             
                                <div class="col-md-12">
                                    <input type="submit" class="btn btn-primary btn-send" value="Ajouter">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <p class="text-muted">
                                        <strong><span style="color: red">* est obligatoire.</span></strong>
                                </div>
                            </div>
                        </div>
    
                    </form>
            </div>
        </div>
      </div>
@endsection

resources/views/Entretien-view/index.blade.php
@extends('layouts.app')

@section('title')
index Entretiens 
@endsection
   
@section('content')

<center>
    <h1 class="mt-4"><span class="text-uppercase">LISTE DES Entretiens</span></h1>
</center>
<div class="container">
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active"><a href="/Entretien">Entretiens</a> </li>
    </ol>
</div>

@can('create entretien')
    <center>
        <a href="{{ route('Entretien.create') }}" style="font-size: 20px" class="btn btn-primary"><i class="fas fa-plus-square" ></i> <span>Ajouter une Entretien</span></a>
    </center>
@endcan
<BR>
<div class="col-md-12">
    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover" id="dataTable" width="100%" cellspacing="0">
                    <thead class="text-primary">
    <tr>
        <td style="border:none;white-space: nowrap" class="text-uppercase">#</td>
        <td style="border:none;white-space: nowrap" class="text-uppercase">Vehicule</td>
        <td style="border:none;white-space: nowrap" class="text-uppercase">Chauffeure</td>
        <td style="border:none;white-space: nowrap" class="text-uppercase">Date</td>
        <td style="border:none;white-space: nowrap" class="text-uppercase">Carburant</td>
        <td style="border:none;white-space: nowrap" class="text-uppercase">N Souche</td>
        <td style="border:none;white-space: nowrap" class="text-uppercase">Object</td>
        <td style="border:none;white-space: nowrap" class="text-uppercase">Kelometrage</td>
        <td style="border:none;white-space: nowrap" class="text-uppercase">Benificiere</td>
        <td style="border:none;white-space: nowrap" class="text-uppercase">Observation</td>
        @can('edit entretien')
            <td style="border:none;white-space: nowrap" class="text-uppercase">Action</td>
        @endcan
    </tr> 
</thead>
<tbody id="myTable">    
    @forelse($Entretiens as $Entretien)
    <tr>
        <td style="white-space: nowrap">
            <a>{{$Entretien->id}}</a>
        </td>
        <td style="white-space: nowrap">
                @if ($Entretien->vehicule_id == null)
                    <span style="color: red">---</span>
                @else
                    @foreach ($liste_vehicule as $vehicule)
                        @if ( $Entretien->vehicule_id == $vehicule->id)

                            @if ($vehicule->type == "Voiture")
                                <i class="fas fa-car"></i>
                            @else
                                @if ($vehicule->type == "Moto" || $vehicule->type == "Velo")
                                    <i class="fas fa-bicycle"></i>    
                                @else
                                    @if ($vehicule->type == "Bus" || $vehicule->type == "MiniBus")
                                    <i class="fas fa-bus-alt"></i>                   
                                    @endif                
                                @endif
                            @endif

                            {{ $vehicule->marque}} : {{ $vehicule->immatriculation }}
                        @endif
                    @endforeach
                @endif
        </td>
        <td style="white-space: nowrap">
                @if ($Entretien->chauffeure_id == null)
                    <span style="color: red">---</span>
                @else
                    @foreach ($liste_chauffeure as $chauffeure)
                        @if ( $Entretien->chauffeure_id == $chauffeure->id)
                            {{ $chauffeure->prenom }} {{ $chauffeure->nom }}
                        @endif
                    @endforeach
                @endif
        </td>
        <td style="white-space: nowrap">
                @if ($Entretien->date == null)
                    <span style="color: red">---</span>
                @else
                    {{$Entretien->date}}
                @endif
        </td>
        <td style="white-space: nowrap">
                @if ($Entretien->montant_Carburant == null)
                    <span style="color: red">---</span>
                @else
                    {{$Entretien->montant_Carburant}} DH
                @endif
        </td>
        <td style="white-space: nowrap">
                @if ($Entretien->N_Souche == null)
                    <span style="color: red">---</span>
                @else
                    {{$Entretien->N_Souche}}
                @endif
        </td>
        <td style="white-space: nowrap">
                @if ($Entretien->object == null)
                    <span style="color: red">---</span>
                @else
                    {{$Entretien->object}}
                @endif
        </td>
        <td style="white-space: nowrap">
                @if ($Entretien->kelometrage == null)
                    <span style="color: red">---</span>
                @else
                    {{$Entretien->kelometrage}} kilo
                @endif
        </td>
        <td style="white-space: nowrap">
                @if ($Entretien->Garage_id == null)
                    <span style="color: red">---</span>
                @else
                    @foreach ($liste_garage as $garage)
                        @if ( $garage->id == $Entretien->Garage_id)
                            {{ $garage->NomGarage }} 
                        @endif
                    @endforeach
                @endif
        </td>
        <td style="white-space: nowrap">
            @if ($Entretien->observation == null)
                <span style="color: red">---</span>
            @else
                {{ mb_strimwidth("$Entretien->observation",0,10,"...")  }}
            @endif
        </td>

        @can('edit entretien')
        <td style="white-space: nowrap">
            <center>
                <a href="{{ route('Entretien.edit' , $Entretien->id ),'/edit' }}" class="Edit" title="edit" data-toggle="tooltip"><i class="fas fa-edit fa-lg"></i></i></a>
                {{-- <a href="" class="delete" title="Supprimer" data-toggle="modal" data-target="#exampleModal-{{ $Entretien->id }}" data-whatever="{{ $Entretien->id }}"><i class="fas fa-trash-alt fa-lg"></i></a> --}}
            
                    {{-- Model --}}
                    {{-- <div class="modal fade" id="exampleModal-{{ $Entretien->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <form method="POST" action="{{ route('Entretien.destroy' , $Entretien->id ) }}" role="form">
                            @csrf
                            @method('DELETE')
                            <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">confirmation</h5>
                                <input type="hidden" name="dele" value="{{ $Entretien->id }}">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                </div>
                                <div class="modal-body">
                                    <h3> voulez vous supprimer la Entretien <br> 
                                        Referance : {{ $Entretien->id }}</h3>
                                </div>
                                <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <input type="submit" class="btn btn-danger btn-send" value="Supprimer">
                                </div>
                            </div>
                            </div>
                        </form>
                    </div> --}}

            </center>
        </td>   
        @endcan

    </tr>

    @empty
    <tr>
        <td colspan="11">
            <div class="card-header"><strong style="color: red"> <center>Aucune Entretien</center> </strong> </div>
        </td>
    </tr>
        
    @endforelse  
    
</tbody>
</table>

</div>
</div>
</div>        
</div>

@endsection